# Linter, that we were forced to switch to, doesn't allow disabling
# of linting of test files as a cli argument.
# (It does have useless --tests flag to enable the already enabled
# linting of tests, while --tests false is interpreted incorrectly)
#
# Just make a file config for it and hope that one day all software will burn
run:
  tests: false
